//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlDbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supermarket_chainEntities : DbContext
    {
        public supermarket_chainEntities()
            : base("name=supermarket_chainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<expens> expenses { get; set; }
        public DbSet<vendor> vendors { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<vendors_products> vendors_products { get; set; }
    }
}
